remote_theme: mmistakes/minimal-mistakes

include:
  - _pages
  
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

# Your site info
title: Vaynee Sungeelee
description: Data Scientist & HCI Researcher
url: "https://vaynees.github.io"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single

